import React,{useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Heart,X,MapPin,MessageCircle,Plus,Leaf,Store,User,Search,SlidersHorizontal,Sparkles,Camera,ChevronRight,ArrowLeft,Send,Check,ImagePlus,Navigation,Star}from'lucide-react';
import'./style.css';

const seedPlants=[
{id:1,name:'Monstera Albo',kind:'Rooted cutting',km:2.4,owner:'Maya',want:'Philodendron Pink Princess',match:true,img:'https://images.unsplash.com/photo-1614594575810-10e307c34c75?auto=format&fit=crop&w=1000&q=85'},
{id:2,name:'Philodendron Brasil',kind:'Mature plant',km:4.8,owner:'Noa',want:'Open to offers',match:false,img:'https://images.unsplash.com/photo-1612363148951-15f16817648f?auto=format&fit=crop&w=1000&q=85'},
{id:3,name:'Golden Pothos',kind:'3 cuttings',km:6.1,owner:'Dan',want:'Monstera / herbs',match:true,img:'https://images.unsplash.com/photo-1597055181300-e3633a917c9c?auto=format&fit=crop&w=1000&q=85'},
{id:4,name:'Bird of Paradise',kind:'Young plant',km:8.7,owner:'Shir',want:'Calathea',match:false,img:'https://images.unsplash.com/photo-1593691509543-c55fb32e5cee?auto=format&fit=crop&w=1000&q=85'}];
const nurseries=[['The Green House','1.8 km','Tropical plants · Pots · Soil'],['Urban Jungle','3.2 km','Rare plants · Cuttings · Workshops'],['Botanica','5.6 km','Indoor plants · Planters · Delivery']];
function App(){
 const[tab,setTab]=useState('discover'),[i,setI]=useState(0),[radius,setRadius]=useState(10),[showFilters,setShowFilters]=useState(false),[showAdd,setShowAdd]=useState(false),[showWish,setShowWish]=useState(false),[activeChat,setActiveChat]=useState(null);
 const[plants,setPlants]=useState(seedPlants),[wishlist,setWishlist]=useState(['Thai Constellation','Pink Princess']),[matches,setMatches]=useState([{id:99,owner:'Lior',name:'Monstera Adansonii',msg:'It’s a match — say hello 🌿',img:seedPlants[1].img}]);
 const[myPlants,setMyPlants]=useState([{id:'mine1',name:'Monstera Deliciosa',kind:'Mature plant',want:'Pink Princess',img:seedPlants[2].img}]);
 const p=plants[i%plants.length];
 const swipe=(yes)=>{if(yes&&p.match){setMatches(m=>m.some(x=>x.id===p.id)?m:[{id:p.id,owner:p.owner,name:p.name,msg:'It’s a match — say hello 🌿',img:p.img},...m]);setActiveChat({match:p,celebrate:true});}else setI(x=>x+1)};
 const filtered=useMemo(()=>plants.filter(x=>x.km<=radius),[plants,radius]);
 const next=()=>setI(x=>x+1);
 return <div className="app">
 <header><div className="brand"><span className="mark">L</span><b>LEAFLOOP</b></div><button className="round" onClick={()=>setShowFilters(true)}><SlidersHorizontal size={19}/></button></header>
 <main>
 {tab==='discover'&&<><div className="hello"><div><small>DISCOVER NEAR YOU</small><h1>Find your next<br/><em>plant crush.</em></h1></div><button className="radius" onClick={()=>setShowFilters(true)}><MapPin size={14}/> {radius} km</button></div>
 {filtered.length?<><div className="card"><img src={p.img}/><div className="shade"/><div className="badges"><span>AVAILABLE</span><span className="soft">{p.kind}</span></div><div className="info"><div className="distance"><MapPin size={15}/>{p.km} km · {p.owner}</div><h2>{p.name}</h2><div className="want"><span>LOOKING FOR</span><b>{p.want}</b></div></div></div><div className="actions"><button onClick={()=>swipe(false)} className="no"><X/></button><button className="save" onClick={()=>setWishlist(w=>w.includes(p.name)?w:[...w,p.name])}><Sparkles/></button><button onClick={()=>swipe(true)} className="yes"><Heart fill="currentColor"/></button></div></>:<div className="empty">No plants inside this radius yet.</div>}
 <section className="wish"><div><small>YOUR WISHLIST</small><h3>Plants you're dreaming about</h3></div><button onClick={()=>setShowWish(true)}>View all <ChevronRight size={16}/></button><div className="wishrow">{wishlist.slice(0,3).map(x=><div className="wishplant" key={x}>🌿 <span>{x}</span></div>)}</div></section></>}
 {tab==='nurseries'&&<><div className="hello"><div><small>LOCAL GUIDE</small><h1>Great nurseries,<br/><em>close to home.</em></h1></div></div><div className="search"><Search/> Search nurseries or plants</div>{nurseries.map((n,k)=><div className="nursery" key={n[0]}><div className={'nphoto n'+k}></div><div><small>{n[1]} AWAY</small><h3>{n[0]}</h3><p>{n[2]}</p><span>{k===0?'Featured nursery':'View nursery'}</span></div></div>)}<div className="businessCta"><Store/><div><b>Own a nursery?</b><p>Reach nearby plant lovers and promote new arrivals.</p></div><ChevronRight/></div></>}
 {tab==='matches'&&<><div className="hello"><div><small>CONNECTIONS</small><h1>Your <em>matches.</em></h1></div></div><div className="matchlist">{matches.map((x,k)=><button className="matchitem" key={x.id} onClick={()=>setActiveChat({match:x})}><img src={x.img}/><div><h3>{x.owner} · {x.name}</h3><p>{x.msg}</p></div><b>{k?'2m':'now'}</b></button>)}</div></>}
 {tab==='profile'&&<><div className="profileHero"><div className="avatar">N</div><h2>Netanel</h2><p><MapPin size={14}/> Kfar Saba</p><button>Edit profile</button></div><div className="stats"><div><b>{myPlants.length}</b><span>Plants</span></div><div><b>{matches.length}</b><span>Matches</span></div><div><b>4.9</b><span>Rating</span></div></div><section className="panel"><div className="panelTitle"><div><h3>My plants</h3><p>Every plant gets its own swap card.</p></div><button onClick={()=>setShowAdd(true)}><Camera/> Add</button></div>{myPlants.map(x=><div className="myplant" key={x.id}><img src={x.img}/><div><b>{x.name}</b><span>{x.kind}</span><small>Looking for {x.want}</small></div><span className="live">LIVE</span></div>)}</section><section className="panel compact" onClick={()=>setShowWish(true)}><div><h3>My wishlist</h3><p>{wishlist.length} dream plants</p></div><ChevronRight/></section></>}
 </main>
 <nav><button onClick={()=>setTab('discover')} className={tab==='discover'?'active':''}><Leaf/><span>Discover</span></button><button onClick={()=>setTab('nurseries')} className={tab==='nurseries'?'active':''}><Store/><span>Nurseries</span></button><button className="add" onClick={()=>setShowAdd(true)}><Plus/></button><button onClick={()=>setTab('matches')} className={tab==='matches'?'active':''}><MessageCircle/><span>Matches</span>{matches.length>0&&<i>{matches.length}</i>}</button><button onClick={()=>setTab('profile')} className={tab==='profile'?'active':''}><User/><span>Profile</span></button></nav>
 {showFilters&&<Sheet title="Discovery settings" close={()=>setShowFilters(false)}><label className="fieldLabel">SEARCH RADIUS <b>{radius} km</b></label><input className="range" type="range" min="2" max="50" value={radius} onChange={e=>setRadius(+e.target.value)}/><div className="mapFake"><Navigation/><b>Kfar Saba</b><span>Exact address stays private</span></div><button className="primary" onClick={()=>setShowFilters(false)}>Show plants within {radius} km</button></Sheet>}
 {showWish&&<Sheet title="My wishlist" close={()=>setShowWish(false)}><p className="muted">Add plants you’d love to own. We’ll surface nearby listings first.</p><WishAdder onAdd={v=>setWishlist(w=>w.includes(v)?w:[...w,v])}/>{wishlist.map(x=><div className="wishline" key={x}><span>🌿</span><div><b>{x}</b><small>Alert me when listed nearby</small></div><Check/></div>)}</Sheet>}
 {showAdd&&<AddPlant close={()=>setShowAdd(false)} save={x=>{setMyPlants(m=>[x,...m]);setShowAdd(false);setTab('profile')}}/>}
 {activeChat&&activeChat.celebrate?<div className="modal"><div className="matchbox"><small>PLANT CONNECTION</small><h2>It's a <em>match.</em></h2><div className="pair"><img src={activeChat.match.img}/><div>↔</div><img src={myPlants[0].img}/></div><p>You both have something the other person wants.</p><button onClick={()=>setActiveChat({match:activeChat.match})}>Start chatting</button><a onClick={()=>{setActiveChat(null);next()}}>Keep browsing</a></div></div>:activeChat&&<Chat data={activeChat.match} close={()=>setActiveChat(null)}/>} 
 </div>
}
function Sheet({title,close,children}){return <div className="overlay" onMouseDown={close}><div className="sheet" onMouseDown={e=>e.stopPropagation()}><div className="sheetHead"><h2>{title}</h2><button onClick={close}><X/></button></div>{children}</div></div>}
function WishAdder({onAdd}){const[v,setV]=useState('');return <div className="adder"><input value={v} onChange={e=>setV(e.target.value)} placeholder="Search a plant…"/><button onClick={()=>{if(v.trim()){onAdd(v.trim());setV('')}}}><Plus/></button></div>}
function AddPlant({close,save}){const[name,setName]=useState(''),[kind,setKind]=useState('Rooted cutting'),[want,setWant]=useState('Open to offers'),[img,setImg]=useState(seedPlants[0].img);return <Sheet title="Add a plant" close={close}><div className="upload" onClick={()=>setImg(seedPlants[(Math.floor(Math.random()*seedPlants.length))].img)}><img src={img}/><div><ImagePlus/><b>Tap to choose a photo</b><span>Demo uses a sample photo</span></div></div><label className="fieldLabel">PLANT NAME</label><input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Monstera deliciosa"/><label className="fieldLabel">WHAT ARE YOU OFFERING?</label><select className="input" value={kind} onChange={e=>setKind(e.target.value)}><option>Rooted cutting</option><option>Mature plant</option><option>Young plant</option><option>Seeds</option></select><label className="fieldLabel">WHAT WOULD YOU LIKE?</label><input className="input" value={want} onChange={e=>setWant(e.target.value)}/><button className="primary" disabled={!name.trim()} onClick={()=>save({id:Date.now(),name,kind,want,img})}>Publish swap card</button></Sheet>}
function Chat({data,close}){const[msg,setMsg]=useState(''),[messages,setMessages]=useState(['Hey! I’d love to swap 🌿']);return <div className="chat"><div className="chatHead"><button onClick={close}><ArrowLeft/></button><img src={data.img}/><div><b>{data.owner}</b><span>{data.name}</span></div></div><div className="trade"><img src={data.img}/><div><small>YOUR MATCH</small><b>{data.name}</b></div><span>↔</span></div><div className="messages">{messages.map((x,k)=><div className={k?'bubble mine':'bubble'} key={k}>{x}</div>)}</div><div className="composer"><input value={msg} onChange={e=>setMsg(e.target.value)} placeholder="Message…" onKeyDown={e=>{if(e.key==='Enter'&&msg.trim()){setMessages(m=>[...m,msg]);setMsg('')}}}/><button onClick={()=>{if(msg.trim()){setMessages(m=>[...m,msg]);setMsg('')}}}><Send/></button></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
